language: python
python:
  - "3.6"

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes
  - conda config --set changeps1 no
  - conda config --add channels jdblischak
  - conda config --add channels defaults
  - conda config --add channels bioconda
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda info -a
  # Install conda packages
  - travis_retry conda install --file=requirements/conda-forge --file=requirements/bioconda --file=requirements/jdblischak

before_script:
  - conda list
  - dsc --version

script:
  - cd dsc/
  - dsc benchmark.dsc -h
  - dsc benchmark.dsc --truncate
