version: 2
jobs:
  build:
    working_directory: /dsc-log-fold-change
    docker:
      - image: continuumio/miniconda3:4.3.27p0
    steps:
      - checkout
      - run:
          name: Installation
          command: |
            conda config --set always_yes yes
            conda config --set quiet yes
            conda config --set changeps1 no
            conda config --set auto_update_conda no
            conda config --add channels jdblischak
            conda config --add channels defaults
            conda config --add channels bioconda
            conda config --add channels conda-forge
            conda info -a
            # Install conda packages
            conda env create --file environment.yaml
            conda list -n dsc-log-fold-change
      - run:
          name: Run DSC
          command: |
            source activate dsc-log-fold-change
            cd dsc/
            dsc --version
            dsc benchmark.dsc -h
            dsc benchmark.dsc --truncate
      - store_artifacts:
          path: dsc/benchmark/
      - store_artifacts:
          path: dsc/benchmark.html

